### ISSUE TITLE
SHR Oncology ToxicReactionToTreatment should just be ToxicReaction?

### ISSUE THREAD

**Issue by gregquinn2001** [standardhealth/shr_spec#59] opened 2017-10-26 01:10 UTC
From the specification of our structured phrases, we need a ToxicReaction class with an Attribution attribute. It looks like ToxicReactionToTreatment does contain an AdverseEvent which can have a CauseCategory which is the original list of attribution values.

A ToxicReactionToTreatment can be caused by the disease instead of treatment?

I think we should rename ToxicReactionToTreatment back to ToxicReaction

**Comment by markkramerus** [comment] 2017-10-28 21:20
An adverse reaction is by definition a reaction to an intervention, so I agree "ToTreatment" is redundant. Removed in my active branch. Should be committed to Main by the end of the current sprint. 
(PS - Reaction to the disease is a sign or symptom or manifestation. It would not be considered an adverse reaction)

**Comment by gregquinn2001** [comment] 2017-10-28 23:01
We need to be able to capture toxic reactions and attribute them to a suspected reason. Are you saying we have to use different entries based on attribution? Tell me how I would model a toxic reaction to treatment and a toxic reaction to the disease in SHR please.

**Comment by markkramerus** [comment] 2017-10-29 14:50
I'm saying there is no such thing as toxic reaction to disease.

**Comment by gregquinn2001** [comment] 2017-10-29 16:19
I guess Monica disagrees as I understand. We have a requirement to store a toxicity with an associated attribution of disease or treatment. I guess we could use 2 different elements to store them if that's what SHR dictates, but we need a way to store both cases.

**Comment by jsnichols** [comment] 2017-10-29 16:31
From my POV, this is a terminology problem. 

We are capturing adverse events as represented in the CTCAE coding system.

An adverse event, broadly, is "something bad that happens" (in the case of CTCAE, to a patient in a clinical trial)

Adverse events nay drive from the disease, treatment, or other sources, sometimes unknown. 

"Toxicity" is outdated terminology. It's easier if you don't use the term. If you must, restrict its use to "adverse events that drive from treatments" ie. iatrogenic effects.

**Comment by markkramerus** [comment] 2017-11-01 16:04
Adverse Event is agnostic to cause. Adverse Reaction, however, assigns a cause (possible or probable). The issue is, whether AdverseReaction can be attributed to the natural course of disease. I’d say not.  I took it from the term "Toxic Reaction" that we were dealing with the latter.

**Comment by rutemartins** [comment] 2019-01-16 21:19
This issue has been overcome by recent developments. In the current `dev` branch, `AdverseEvent` is associated with `0..* CausalAttribution`, which in turn has a `CauseCategory`, defined as "whether the adverse event is attributed to a treatment, course of the disease, unrelated to either, or unknown.". There's no longer an `AdverseReaction`.

**Comment by gregquinn2001** [comment] 2019-01-16 21:47
Sounds great! Thanks @markkramerus  and @rutemartins

**Comment by markkramerus** [comment] 2019-08-06 17:38
Overcome by events. Not a requirement in mCODE

**Closed by markkramerus** 2019-08-06 17:38 UTC
Labels: fixed in dev
